import * as THREE from "three";

export const PhysicalMaterial = (
  basicParams = {
    color: 0x121212,
    emissive: 0x000000,
    sheenColor: 0x000000,
    sheen: 0,
    sheenRoughness: 0,
    specularColor: 0x000000,
    specularIntensity: 0,
    roughness: 1,
    roughnessMap: null,
    metalness: 0,
    metalnessMap: null,
    ior: 0,
    reflectivity: 0,
    iridescence: 0,
    iridescenceIOR: 0,
    iridescenceMap: null,
    clearcoat: 0,
    clearcoatRoughness: 0,
    opacity: 1,
    visible: true,
  },
  CustomParams = {
    side: THREE.FrontSide,
    fog: true,
    map: null,
    envMap: null,
    alphaMap: null,
    combine: THREE.AddOperation,
    reflectivity: 0.5,
    refractionRatio: 0.5,
    wireframe: false,
    flatShading: false,
    vertexColors: false,
  },
  admin = {
    alphaTest: 0,
    alphaHash: false,
    depthTest: false,
    depthWrite: false,
  }
) => {
  return new THREE.MeshPhysicalMaterial({
    color: basicParams.color,
    emissive: basicParams.emissive,
    sheenColor: basicParams.sheenColor,
    sheen: basicParams.sheen,
    sheenRoughness: basicParams.sheenRoughness,
    specularColor: basicParams.specularColor,
    specularIntensity: basicParams.specularIntensity,
    roughness: basicParams.roughness,
    roughnessMap: basicParams.roughnessMap,
    metalness: basicParams.metalness,
    metalnessMap: basicParams.metalnessMap,
    ior: basicParams.ior,
    reflectivity: basicParams.reflectivity,
    iridescence: basicParams.iridescence,
    iridescenceIOR: basicParams.iridescenceIOR,
    iridescenceMap: basicParams.iridescenceMap,
    clearcoat: basicParams.clearcoat,
    clearcoatRoughness: basicParams.clearcoatRoughness,
    visible: basicParams.visible,
    transparent: basicParams.opacity < 1,
    opacity: basicParams.opacity,

    fog: CustomParams.fog,
    map: CustomParams.map,
    envMap: CustomParams.envMap,
    alphaMap: CustomParams.alphaMap,
    combine: CustomParams.combine,
    reflectivity: CustomParams.reflectivity,
    refractionRatio: CustomParams.refractionRatio,
    wireframe: CustomParams.wireframe,
    flatShading: CustomParams.flatShading,
    vertexColors: CustomParams.vertexColors,

    alphaTest: admin.alphaTest,
    alphaHash: admin.alphaHash,
    depthTest: admin.depthTest,
    depthWrite: admin.depthWrite,
  });
};
