export const StandardMaterial = (
    visual = {
      color: 0xffffff,
      roughness: 1,
      metalness: 0,
      map: null,
      lightMap: null,
      lightMapIntensity: 1,
      aoMap: null,
      aoMapIntensity: 1,
      emissive: 0x000000,
      emissiveIntensity: 1,
      emissiveMap: null,
      bumpMap: null,
      bumpScale: 1,
      normalMap: null,
      normalScale: new THREE.Vector2(1, 1),
      displacementMap: null,
      displacementScale: 1,
      displacementBias: 0,
      roughnessMap: null,
      metalnessMap: null,
      alphaMap: null,
      envMap: null,
      refractionRatio: 0.98,
    },
    admin = {
      wireframe: false,
      wireframeLinewidth: 1,
      side: THREE.FrontSide,
      flatShading: false,
      fog: true,
    },
    animate = {
      skinning: false,
      morphTargets: false,
      morphNormals: false,
    }
  ) => {
    return new THREE.MeshStandardMaterial({
      color: visual.color,
      roughness: visual.roughness,
      metalness: visual.metalness,
      map: visual.map,
      lightMap: visual.lightMap,
      lightMapIntensity: visual.lightMapIntensity,
      aoMap: visual.aoMap,
      aoMapIntensity: visual.aoMapIntensity,
      emissive: visual.emissive,
      emissiveIntensity: visual.emissiveIntensity,
      emissiveMap: visual.emissiveMap,
      bumpMap: visual.bumpMap,
      bumpScale: visual.bumpScale,
      normalMap: visual.normalMap,
      normalScale: visual.normalScale,
      displacementMap: visual.displacementMap,
      displacementScale: visual.displacementScale,
      displacementBias: visual.displacementBias,
      roughnessMap: visual.roughnessMap,
      metalnessMap: visual.metalnessMap,
      alphaMap: visual.alphaMap,
      envMap: visual.envMap,
      refractionRatio: visual.refractionRatio,
      
      wireframe: admin.wireframe,
      wireframeLinewidth: admin.wireframeLinewidth,
      side: admin.side,
      flatShading: admin.flatShading,
      fog: admin.fog,

      skinning: animate.skinning,
      morphTargets: animate.morphTargets,
      morphNormals: animate.morphNormals,
    });
  };
  